CREATE DATABASE LIBRARY_DB;
USE LIBRARY_DB;

CREATE TABLE GENRE (
	ID int PRIMARY KEY AUTO_INCREMENT,
	GENRENAME VARCHAR(100) NOT NULL
);

CREATE TABLE AUTHOR (
	ID int PRIMARY KEY AUTO_INCREMENT,
	FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL
);

CREATE TABLE BOOK (
	ID int PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
    GENREID VARCHAR(50) NOT NULL,
    AUTHORID VARCHAR(50) NOT NULL,
    
	FOREIGN KEY (GENREID) REFERENCES GENRE(ID),
	FOREIGN KEY (AUTHORID) REFERENCES AUTHOR(ID)
);

