CREATE DATABASE LIBRARY_DB;
USE LIBRARY_DB;

CREATE TABLE Genre (
	id INT PRIMARY KEY AUTO_INCREMENT,
	genre_name VARCHAR(100) NOT NULL
);

CREATE TABLE Author (
	id int PRIMARY KEY AUTO_INCREMENT,
	first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE Book (
	id int PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
    genre_id INT NOT NULL,
    author_id INT NOT NULL,
    
	FOREIGN KEY (genre_id) REFERENCES Genre(id),
	FOREIGN KEY (author_id) REFERENCES Author(id)
);

