USE LIBRARY_DB;

INSERT INTO Genre (genre_name) 
VALUES 
	("Romance"), 
    ("Action"), 
    ("Fantasy"), 
    ("Sci-Fi"), 
    ("Dystpian"), 
    ("Adventure"), 
    ("Comedy"), 
    ("Mystery"), 
    ("Horror"), 
    ("True Crime");

INSERT INTO Author (first_name, last_name)
VALUES 
	("Anika", "Hussain"), 
    ("Nathan", "Hayes"), 
    ("Joseph", "Rice"), 
    ("Oscar", "Ip");

SELECT * FROM Author;

INSERT INTO Book (title, genre_id, author_id)
VALUES
	("Horrid Henry", 10, 1),
    ("Truth, Dare or Handcuffs", 10, 3),
    ("Echoes of the Stars", 8, 3),
    ("Letters to a Stranger", 1, 4),
    ("Fragments of a Dream", 7, 1),
    ("Notes from the Underground", 6, 3),
    ("The Art of Simple Living", 9, 2),
    ("Whispers from the Abyss", 9, 4),
    ("The Lost Kingdom", 3, 1),
    ("Chasing Shadows", 8, 2),
    ("Heartstrings", 1, 4),
    ("Into the Abyss", 9, 3),
    ("The Timekeeper's Tale", 4, 2),
    ("Secrets of the Forest", 6, 1),
    ("Murder at Midnight", 8, 4),
    ("The Last Stand", 5, 3),
    ("Echoes of the Past", 7, 1),
    ("The Unseen World", 2, 4),
      ("Whispers in the Wind", 1, 2),
    ("The Hidden Realm", 3, 1),
    ("Beyond the Horizon", 6, 3),
    ("The Phantom's Curse", 9, 4),
    ("Journey to the Stars", 4, 2),
    ("Shattered Dreams", 7, 1),
    ("The Silent Witness", 8, 3),
    ("The Abyssal Depths", 9, 4),
    ("Chronicles of the Brave", 5, 1),
    ("Secrets of the City", 6, 2),
    ("The Enigma", 8, 3),
    ("Love in the Time of Chaos", 1, 4),
    ("Adventures in Time", 4, 1),
    ("The Cursed Pendant", 3, 2),
    ("Echoes of Eternity", 7, 3),
    ("The Masquerade Ball", 1, 4),
    ("Labyrinth of Lies", 8, 1),
    ("Into the Wild", 6, 2),
    ("Fallen Angels", 5, 3),
    ("The Enchanted Garden", 3, 4),
    ("Dancing with Shadows", 9, 1),
    ("Love in the Dark", 1, 2),
    ("The Time Traveler's Legacy", 4, 3),
    ("Mysteries of the Deep", 8, 4),
    ("The Great Escape", 5, 1),
    ("Veil of Secrets", 6, 2),
    ("The Dreamer's Journey", 7, 3),
    ("Whirlwind Adventures", 6, 4),
    ("The Mirror's Reflection", 8, 1),
    ("Riddles of the Past", 9, 2),
    ("Underworld Chronicles", 3, 3),
    ("Tales of the Unseen", 1, 4),
    ("The Gathering Storm", 5, 2),
    ("Echoes of the Forgotten", 6, 1),
    ("The Last Prophecy", 4, 3),
    ("The Haunting Melody", 9, 4),
    ("Secrets Beneath the Surface", 8, 1),
    ("Whispers of the Heart", 1, 2),
    ("The Forgotten Island", 5, 3),
    ("Veil of Illusions", 4, 2),
    ("Beneath the Stars", 6, 1),
    ("The Keeper of Secrets", 8, 4),
    ("Shadows in the Night", 9, 3),
    ("The Boundless Sky", 7, 2),
    ("Hearts in Conflict", 1, 1),
    ("The Dark Forest", 3, 4),
    ("The Last Survivor", 5, 2),
    ("The Quest for Truth", 6, 3),
    ("The Phoenix's Rise", 3, 1),
    ("Chronicles of Courage", 7, 2);
    
    SELECT * FROM Book;